### ISSUE TITLE
It's unclear in the instructions how to uncapture the mouse once it has been captured.

### ISSUE THREAD

**Issue by qeeg** [dirkwhoffmann/vAmigaBM#3]
I can click in the window to make it capture my mouse movements, but once i do that, I can't seem to figure out how to get it uncaptured.

**Comment by dirkwhoffmann** [comment]
Try to shake the mouse. By default the "shake detector" is supposed to be enabled.

**Comment by qeeg** [comment]
...Strange, maybe that should be documented somewhere?

**Comment by qeeg** [comment]
Also, even if I shake the mouse, the cursor is still stuck inside the borders of the window.

**Comment by dirkwhoffmann** [comment]
Sorry for not replying earlier. It's unclear at the moment if this project should be continued or trashed. I've updated the repo with the latest vAmiga core. Now, the mouse can be released by pressing ESC (not a good choice, I know). 

Please consider this project just as a showcase how the vAmiga core can be ported to other platforms.
